# Generated by Django 3.0.4 on 2020-05-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_form_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
