# Generated by Django 3.0.4 on 2020-05-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200506_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
